Test: increase spring autoconfigure module unit test coverage
apache/incubator-seata pull request #6198
Opened 2023-12-22 15:18 UTC by l81893521

- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did

### Ⅱ. Does this pull request fix one issue?
fixes #6199 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-01-10 06:59 UTC, lightClouds917 requested changes

2024-01-10 06:59 UTC, lightClouds917 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/SeataClientEnvironmentPostProcessorTest.java
> + * @date: 2024/1/2
remove author and date

2024-01-15 08:55 UTC, funky-eyes commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/properties/SeataPropertiesTest.java
*PropertiesTest 我希望这些properties的get set的相关方法通过扫描包，解析类，进行反射将其中的method一次性处理掉，至于入参类型可以通过反射拿到参数类型，写一个switch等方式来处理。
*PropertiesTest I want the get set related methods of these properties to scan the package, parse the class, and do reflection to get rid of the method once and for all, and as for the input parameter type can be dealt with by getting the parameter type through reflection, writing a switch, etc.

2024-01-17 05:05 UTC, l81893521 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/SeataClientEnvironmentPostProcessorTest.java
> + * @date: 2024/1/2
fixed

2024-01-18 03:41 UTC, funky-eyes reviewed
*PropertiesTest 我希望这些properties的get set的相关方法通过扫描包，解析类，进行反射将其中的method一次性处理掉，至于入参类型可以通过反射拿到参数类型，写一个switch等方式来处理。
*PropertiesTest I want the get set related methods of these properties to scan the package, parse the class, and do reflection to get rid of the method once and for all, and as for the input parameter type can be dealt with by getting the parameter type through reflection, writing a switch, etc.

2024-07-02 02:33 UTC, lightClouds917 requested changes
remove all author

2024-07-02 02:33 UTC, lightClouds917 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/properties/SagaAsyncThreadPoolPropertiesTest.java
> + * @author: zhangjiawei
remove author

2024-07-02 02:33 UTC, lightClouds917 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/properties/SeataPropertiesTest.java
> + * @author: zhangjiawei
remove author

2024-07-02 02:33 UTC, lightClouds917 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/properties/SpringCloudAlibabaConfigurationTest.java
> + * @author: zhangjiawei
remove author

2024-07-02 02:33 UTC, lightClouds917 commented on seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/test/java/io/seata/spring/boot/autoconfigure/properties/client/LockPropertiesTest.java
> + * @date: 2023/12/22
remove all author

2024-08-19 07:39 UTC, closed without merging