Increase [integration-tx-api] module test case coverage
apache/incubator-seata pull request #6533
Opened 2024-05-12 08:23 UTC by azatyamanaev

- [ ] I have registered the PR [changes](../changes).

### Ⅰ. Describe what this PR did
increase test case coverage of [integration-tx-api] module

### Ⅱ. Does this pull request fix one issue?
fixes #6507 

### Ⅲ. Why don't you add test cases (unit test/integration test)? 

### Ⅳ. Describe how to verify it

### Ⅴ. Special notes for reviews

2024-05-15 09:36 UTC, xingfudeshi commented
Pls register this PR in https://github.com/apache/incubator-seata/tree/2.x/changes

2024-05-15 13:14 UTC, azatyamanaev commented
> Pls register this PR in https://github.com/apache/incubator-seata/tree/2.x/changes

Done

2024-05-16 13:11 UTC, azatyamanaev commented
> Pls register this PR in https://github.com/apache/incubator-seata/tree/2.x/changes

@xingfudeshi Done

2024-05-20 10:07 UTC, azatyamanaev commented
@xingfudeshi Can you resolve merge conflict?

2024-05-20 10:17 UTC, xingfudeshi commented
> @xingfudeshi Can you resolve merge conflict?

Yes.The current version is being released.I'll resolve conflicts after the release.

2024-05-20 10:49 UTC, azatyamanaev commented
> > @xingfudeshi Can you resolve merge conflict?
> 
> Yes.The current version is being released.I'll resolve conflicts after the release.

How long does it usually takes?

2024-05-21 12:49 UTC, xingfudeshi commented
> > > @xingfudeshi Can you resolve merge conflict?
> 
> > 
> 
> > Yes.The current version is being released.I'll resolve conflicts after the release.
> 
> 
> 
> How long does it usually take?


It won’t take long. After version 2.1 is released, I will start addressing the conflicting files in this PR.

2024-06-05 12:00 UTC, lightClouds917 requested changes

2024-06-05 12:00 UTC, lightClouds917 commented on changes/en-us/2.x.md
> +- [[#6533](https://github.com/apache/incubator-seata/pull/6533)] increase integration-tx-api module unit test coverage
alse need to add into zh-cn/2.x.md

2024-06-05 15:44 UTC, azatyamanaev commented on changes/en-us/2.x.md
> +- [[#6533](https://github.com/apache/incubator-seata/pull/6533)] increase integration-tx-api module unit test coverage
Done

2024-06-05 15:46 UTC, azatyamanaev commented on changes/en-us/2.x.md
> +- [[#6533](https://github.com/apache/incubator-seata/pull/6533)] increase integration-tx-api module unit test coverage
> alse need to add into zh-cn/2.x.md

@lightClouds917 Done

2024-06-13 06:18 UTC, lightClouds917 approved these changes
please resolve the conflict

2024-06-13 09:30 UTC, azatyamanaev commented
> please resolve the conflict

i can't, i don't have write access to repository

2024-06-24 06:21 UTC, lightClouds917 commented
> > please resolve the conflict
> 
> I can't, I don't have write access to repository. Or should I rebase my branch?
you can merge the 2.x branch to your branch,and resolve the confict.

2024-06-25 06:46 UTC, justinmclean commented
I've fixed the conflicts for you.

2024-07-01 10:07 UTC, lightClouds917 approved these changes
LGTM

2024-07-05 09:56 UTC, funky-eyes commented
我修复了codecov没有report成功的问题，现在让我们看看目前的单测覆盖度是多少
I've fixed the issue with Codecov not reporting successfully. Now, let's see what the current test coverage percentage is.

2024-07-29 09:39 UTC, funky-eyes approved these changes
LGTM

2024-07-29 09:40 UTC, merged